package com.google.android.gms.common.api.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzcp<R extends Result> extends OptionalPendingResult<R> {
  private final zzs<R> zzfoy;
  
  public zzcp(PendingResult<R> paramPendingResult) {
    if (paramPendingResult instanceof zzs) {
      this.zzfoy = (zzs<R>)paramPendingResult;
      return;
    } 
    throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
  }
  
  public final R await() {
    return (R)this.zzfoy.await();
  }
  
  public final R await(long paramLong, TimeUnit paramTimeUnit) {
    return (R)this.zzfoy.await(paramLong, paramTimeUnit);
  }
  
  public final void cancel() {
    this.zzfoy.cancel();
  }
  
  public final R get() {
    if (super.isDone())
      return (R)super.await(0L, TimeUnit.MILLISECONDS); 
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public final boolean isCanceled() {
    return this.zzfoy.isCanceled();
  }
  
  public final boolean isDone() {
    return this.zzfoy.isReady();
  }
  
  public final void setResultCallback(ResultCallback<? super R> paramResultCallback) {
    this.zzfoy.setResultCallback(paramResultCallback);
  }
  
  public final void setResultCallback(ResultCallback<? super R> paramResultCallback, long paramLong, TimeUnit paramTimeUnit) {
    this.zzfoy.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  @NonNull
  public final <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> paramResultTransform) {
    return this.zzfoy.then(paramResultTransform);
  }
  
  public final void zza(PendingResult.zza paramzza) {
    this.zzfoy.zza(paramzza);
  }
  
  public final Integer zzafs() {
    return this.zzfoy.zzafs();
  }
}


/* Location:              /home/dragonh/workspace/work/app/apk-reverse/dex-tools-2.1/target-dex2jar.jar!/com/google/android/gms/common/api/internal/zzcp.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       1.1.3
 */